[tool.poetry]
name = "mlconfig"
version = "0.1.8"
description = ""
authors = ["なるみ <toucans-cutouts0f@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
omegaconf = "^2.3.0"

[tool.poetry.group.dev.dependencies]
yapf = "^0.40.0"
toml = "^0.10.2"
flake8 = "^6.0.0"
pytest = "^7.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
