[tool.poetry]
name = "mlconfig"
version = "0.1.7"
description = ""
authors = ["なるみ <weaper@gamil.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
