name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Flake8
        run: python -m pip install flake8
      - name: Lint
        run: flake8 --verbose mlconfig
