name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]
        poetry-version: [1.5.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
          
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build -f wheel
          poetry publish -u __token__ -p $PYPI_TOKEN
