name: Python

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        poetry-version: ["1.8.3"]
    steps:
      - 
        uses: actions/checkout@v4
      -
        name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}
      - 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      -
        name: Install dependencies
        run: poetry install
      - 
        name: Lint
        run: poetry run ruff check .
      - 
        name: Test
        run: poetry run pytest -v -s --cov=. --cov-report=xml tests
      - 
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}