name: Python

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.7.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run flake8 -v
      - name: Test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          poetry run pytest -v -s --cov=mlconfig --cov-report=xml tests
          poetry run codecov
